theme: jekyll-theme-cayman
source: /blog/

title: grassleeblog
description: Jeffrey Graessleys Blog
source: /blog/2023/

title: grassleeblog
description: Jeffrey Graessleys Python Projects
source: /learn/2023
